### ISSUE TITLE
更改主题色配置不生效

### ISSUE THREAD

**Issue by tianchaoyang** [anncwb/vben-admin-thin-next#10]
**BUG描述**

更改主题色配置不生效

**环境信息:**
 - 操作系统: Windows10
 - Node版本: 12.13.0
 - vbem-admin-thin-next：2.0.0-rc.17
 - vite-plugin-style-import版本:  0.4.6
 - ant-design-vue版本：2.0.0-rc.8

**重现步骤**

1: 更改build/config/lessModifyVars.ts文件

2: 启动项目发现主题色配置修改不生效

**附加信息**

去除按需加载css插件后,全量引入ant-design.less文件, 主题色配置会生效
可能是 vite-plugin-style-import中的esModule配置未生效?

**Comment by anncwb** [comment]
可以先自己把 

```
 {
        libraryName: 'ant-design-vue',
        esModule: true,
        resolveStyle: (name) => {
          return `ant-design-vue/es/${name}/style/css`;
        },
      },
```

改成

```ts
 {
        libraryName: 'ant-design-vue',
        esModule: true,
        resolveStyle: (name) => {
          return `ant-design-vue/es/${name}/style/index`;
        },
      },

```
