### ISSUE TITLE
项目运行问题

### ISSUE THREAD

**Issue by null1126** [anncwb/vben-admin-thin-next#2]
Vben Admin 2.0 精简版拉下来 通过“npm install"、”npm run serve“ 跟 ”yarn install“ 、 ”yarn serve" 都跑不起来

**Comment by anncwb** [comment]
请先提供下node版本版本，电脑系统环境

**Comment by null1126** [comment]
node v12.18.3

**Comment by null1126** [comment]
系统环境变量给你截屏吗

**Comment by null1126** [comment]
“yarn install” 后在“[4/5] ⠂ esbuild”后就报错了

[5/5] Building fresh packages...
[1/5] ⠂ core-js
[2/5] ⠂ husky
[3/5] ⠂ esbuild
[4/5] ⠂ esbuild
error D:\XZ-Pro\vben-admin-thin-next-main\node_modules\vite-plugin-mock\node_modules\esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments:

**Comment by anncwb** [comment]
尝试以下几点试试
1. 用手机热点安装或者翻墙
2. 参考文档内依赖安装失败的情况
3. 每次重装依赖都需要删除node_modules和lock文件
