### ISSUE TITLE
template下面多个标签tab页无法切换

### ISSUE THREAD

**Issue by fakerBABA** [anncwb/vben-admin-thin-next#20]
### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

template下面多个标签tab页无法切换且会导致所有的路由都无法加载，只有刷新页面才可以解决
类似于下面这种情况:
`<template>
  <span>1</span>
  <span>2</span>
</template>
`
即使很简单的标签也会出现该问题，经过测试再最新版@2.4.2中也会出现该问题

## System Info
- vben admin版本：2.3.0
- Operating System: win10
- Node version:v14.9.0
- Package manager (npm/yarn/pnpm) and version:yarn@1.22.10

**Comment by anncwb** [comment]
这个是由于`Transition`组件，可以看文档常见问题
