### ISSUE TITLE
一级菜单 导航多余了

### ISSUE THREAD

**Issue by yezhugongjue** [anncwb/vben-admin-thin-next#48]
![image](https://user-images.githubusercontent.com/20020869/143993061-5b8b0090-bb24-4e71-9683-aff43a5f2128.png)
菜单只有一级，不应该有下拉框呀，这个在完整版本没出现过
求解

**Comment by zhagkaiyuan-dev** [comment]
初始化项目也发现了这个问题，同问

**Comment by zhagkaiyuan-dev** [comment]
对比完整版本，发现是Breadcrumb.vue 文件中的 filterItem 方法中的少了hideMenu的判断

**Comment by zhagkaiyuan-dev** [comment]
![image](https://user-images.githubusercontent.com/93756797/145134990-60409b3f-7c31-4df8-9613-2d8ec8056f31.png)

**Comment by yezhugongjue** [comment]
谢谢，太厉害了，我回信你收得到？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhagkaiyuan-dev ***@***.***&gt;
发送时间: 2021年12月8日 09:59
收件人: anncwb/vben-admin-thin-next ***@***.***&gt;
抄送: yezhugongjue ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[anncwb/vben-admin-thin-next] 一级菜单 导航多余了 (Issue #48)





 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhagkaiyuan-dev** [comment]
可以的

yezhugongjue ***@***.***> 于2021年12月8日周三 10:02写道：

**Comment by yezhugongjue** [comment]
方便加个联系方式一起学习么

**Comment by yezhugongjue** [comment]
@zhagkaiyuan-dev 方便加个联系方式一起学习么

**Comment by zhagkaiyuan-dev** [comment]
可以啊
