### ISSUE TITLE
所有预览链接 404

### ISSUE THREAD

**Issue by Jerry-CodeHub** [anncwb/vben-admin-thin-next#80]
[vue-vben-admin](https://vvbin.cn/next/) - Full version Chinese site
[vue-vben-admin-gh-pages](https://anncwb.github.io/vue-vben-admin/) - Full version of the github site
[vben-admin-thin-next](https://vvbin.cn/thin/next/) - Simplified Chinese site
[vben-admin-thin-gh-pages](https://anncwb.github.io/vben-admin-thin-next/) -Simplified github site

**Comment by tjlizz** [comment]
https://next.vben.xx996.org/
https://vue.vben.xx996.org/#/
 我镜像了一份,

**Comment by Jerry-CodeHub** [comment]
👍👍👍, 该项目最近似乎没维护了
